# Generated by Django 4.2.13 on 2024-06-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(max_length=30),
        ),
    ]
