# Generated by Django 4.2.13 on 2024-06-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="done_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выполнения"
            ),
        ),
    ]
