# Generated by Django 4.2.13 on 2024-06-16 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("links", "0004_alter_resource_done_datetime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Группы"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тэги"},
        ),
        migrations.AlterField(
            model_name="group",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор группы",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="is_publish",
            field=models.BooleanField(default=True, verbose_name="Статус выполнения"),
        ),
        migrations.AlterField(
            model_name="group",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="links.group",
                verbose_name="Родитель",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(max_length=80, verbose_name="Заголовок группы"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(max_length=80, verbose_name="Заголовок"),
        ),
    ]
