# Generated by Django 4.2.13 on 2024-06-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0006_alter_category_options_alter_group_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagresource",
            options={
                "verbose_name": "Тэг к Ресурсу",
                "verbose_name_plural": "Тэги к Ресурсам",
            },
        ),
    ]
