# Generated by Django 4.2.13 on 2024-06-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0007_alter_tagresource_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TagResource",
        ),
    ]
