# Generated by Django 4.2.13 on 2024-06-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0008_delete_tagresource"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="Tag",
            new_name="tags",
        ),
    ]
